added safeguards

diff --git a/scripts/functions/adb-list-all-devices b/scripts/functions/adb-list-all-devices
--- a/scripts/functions/adb-list-all-devices
+++ b/scripts/functions/adb-list-all-devices
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v adb)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 adb-list-all-devices () (
     if [[ $# != 1 ]]; then echo "State argument must be given!"; exit 1; fi
     # "device" state is the correct state here for authorized devices
diff --git a/scripts/functions/adb-remove-package-named b/scripts/functions/adb-remove-package-named
--- a/scripts/functions/adb-remove-package-named
+++ b/scripts/functions/adb-remove-package-named
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v adb)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 adb-uninstall-package () (
     if [[ $# != 2 ]]; then echo "id, package arguments must be given!"; exit 1; fi
     adb -s $1 uninstall --user 0 $2
diff --git a/scripts/functions/adb-toggle-screen b/scripts/functions/adb-toggle-screen
--- a/scripts/functions/adb-toggle-screen
+++ b/scripts/functions/adb-toggle-screen
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v adb)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 adb-toggle-screen () (
     adb shell input keyevent KEYCODE_POWER
 )
diff --git a/scripts/functions/ffcompress-mp3 b/scripts/functions/ffcompress-mp3
--- a/scripts/functions/ffcompress-mp3
+++ b/scripts/functions/ffcompress-mp3
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v ffmpeg)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 # ffmpeg compress mp3 audio
 ffcompress-mp3 () (
     [[ -z "$*" ]] && return 2 
diff --git a/scripts/functions/ffconcat-video b/scripts/functions/ffconcat-video
--- a/scripts/functions/ffconcat-video
+++ b/scripts/functions/ffconcat-video
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v ffmpeg)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 # ffmpeg concatenate multiple video files into one
 #  INPUTS: files >= 2
 ffconcat-video () (
diff --git a/scripts/functions/ffcrop-mp4 b/scripts/functions/ffcrop-mp4
--- a/scripts/functions/ffcrop-mp4
+++ b/scripts/functions/ffcrop-mp4
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v ffmpeg)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 # convert (X1,Y1) (X2,Y2) coords with X delimiter instead of comma to ffmpeg format (X2-X1,Y2-Y1)
 __xy_rp_to_ffilter_coords () (
     echo "$@" | awk -F'[x ]' '{ print $3-$1":"$4-$2 }';
diff --git a/scripts/functions/ffextract-audio-mp3 b/scripts/functions/ffextract-audio-mp3
--- a/scripts/functions/ffextract-audio-mp3
+++ b/scripts/functions/ffextract-audio-mp3
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v ffmpeg)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 # ffmpeg extract audio from video with audio to mp3
 ffextract-audio-mp3 () (
     [[ -z "$*" ]] && return 2
diff --git a/scripts/functions/ffextract-video-mp4 b/scripts/functions/ffextract-video-mp4
--- a/scripts/functions/ffextract-video-mp4
+++ b/scripts/functions/ffextract-video-mp4
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v ffmpeg)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 # ffmpeg extract video from video with audio to mp3
 ffextract-video-mp4 () (
     [[ -z "$*" ]] && return 2
diff --git a/scripts/functions/ffscale-mp4 b/scripts/functions/ffscale-mp4
--- a/scripts/functions/ffscale-mp4
+++ b/scripts/functions/ffscale-mp4
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v ffmpeg)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 # convert (X,Y) coords with X delimiter instead of comma to ffmpeg format
 __xy_to_ffilter_coords () (
     echo "$1" | awk -Fx '{ print $1":"$2 }';
diff --git a/scripts/functions/fftrim-mp3 b/scripts/functions/fftrim-mp3
--- a/scripts/functions/fftrim-mp3
+++ b/scripts/functions/fftrim-mp3
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v ffmpeg)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 # convert Minutes:Seconds (colon seperated) to seconds
 __hms () (
     echo "$1" | awk -F: '{ print ($1 * 60) + $2 }';
diff --git a/scripts/functions/ffvideofy b/scripts/functions/ffvideofy
--- a/scripts/functions/ffvideofy
+++ b/scripts/functions/ffvideofy
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v ffmpeg)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 ffvideofy () (
     [[ -z "$*" ]] && return 2 
     [[ "$#" -ne 2 ]] && return 2
diff --git a/scripts/functions/ytdl-mp4 b/scripts/functions/ytdl-mp4
--- a/scripts/functions/ytdl-mp4
+++ b/scripts/functions/ytdl-mp4
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ -z "$(command -v yt-dlp)" ]]; then
+    echo "Cannot run $(basename $0) without dependency! Exiting..."
+    exit 1
+fi
+
 # yt-dlp download to mp4
 ytdl-mp4 () (
     [[ -z "$*" ]] && return 2
