added dependency guards

diff --git a/scripts/functions/adb-setup-hotspot-wireless-debug b/scripts/functions/adb-setup-hotspot-wireless-debug
--- a/scripts/functions/adb-setup-hotspot-wireless-debug
+++ b/scripts/functions/adb-setup-hotspot-wireless-debug
@@ -2,6 +2,11 @@
 
 # HELP setup adb to work with usb debugging (over hotspot)
 
+if [[ -z "$(command -v adb)" ]]; then
+    echo "Cannot run $(basename $0) without adb! Exiting..."
+    exit 1
+fi
+
 adb-setup-hotspot-wireless-debug () (
     if [[ $# != 1 ]]; then echo "device ip must be given!"; exit 1; fi
     adb tcpip 5555 | exit
diff --git a/scripts/functions/ip-all-connected-ipv4 b/scripts/functions/ip-all-connected-ipv4
--- a/scripts/functions/ip-all-connected-ipv4
+++ b/scripts/functions/ip-all-connected-ipv4
@@ -2,6 +2,16 @@
 
 # HELP list all connected devices (except self) ipv4
 
+if [[ -z "$(command -v nmap)" ]]; then
+    echo "Cannot run $(basename $0) without tr! Exiting..."
+    exit 1
+fi
+
+if [[ -z "$(command -v awk)" ]]; then
+    echo "Cannot run $(basename $0) without awk! Exiting..."
+    exit 1
+fi
+
 ip-all-devices-ipv4 () (
     if [[ $# != 1 ]]; then echo "interface ip argument must be given!"; exit 1; fi
     nmap -n -sn "$1/24" -oG - | awk '/Up$/{print $2}' | grep --invert-match "$1"
diff --git a/scripts/functions/ip-all-interfaces-ipv4 b/scripts/functions/ip-all-interfaces-ipv4
--- a/scripts/functions/ip-all-interfaces-ipv4
+++ b/scripts/functions/ip-all-interfaces-ipv4
@@ -2,6 +2,21 @@
 
 # HELP list all connected ethernet interfaces (except self) ipv4
 
+if [[ -z "$(command -v ip)" ]]; then
+    echo "Cannot run $(basename $0) without ip! Exiting..."
+    exit 1
+fi
+
+if [[ -z "$(command -v jq)" ]]; then
+    echo "Cannot run $(basename $0) without jq! Exiting..."
+    exit 1
+fi
+
+if [[ -z "$(command -v tr)" ]]; then
+    echo "Cannot run $(basename $0) without tr! Exiting..."
+    exit 1
+fi
+
 ip-all-interfaces-ipv4 () (
     ip --json -brief address | jq '.[]."addr_info".[0].local | select(. != null and . != "127.0.0.1")' | tr -d '"'
 )
