added sanity check for swap flush

diff --git a/scripts/functionz/swap-flush b/scripts/functionz/swap-flush
--- a/scripts/functionz/swap-flush
+++ b/scripts/functionz/swap-flush
@@ -2,25 +2,40 @@
 
 # HELP flush /swapfile; DANGEROUS, will NOT check if /swapfile contents fit in memory!
 
-# TODO add check if swap_used is more than the Mem: total - used via `free -m`
-
-swap_used=$(free -m | awk '{ print $1 " " $3 }' | grep -i 'swap' | awk '{ print $2 }')
+swap_used="$(free -m | awk '/Swap:/{ print $3 }')"
 
 _depends-on free awk grep swapon swapoff || exit
 
 if [[ -z "$swap_used" ]]; then
-    echo "FATAL ERROR: USAGE VARIABLE IS EMPTY: $swap_used, CANNOT CONTINUE!"
+    echo "FATAL ERROR: SWAP USED IS EMPTY: $swap_used, CANNOT CONTINUE!" 1>&2
     exit 1
 fi
 
 if ! [ "$swap_used" -eq "$swap_used" ] 2>/dev/null; then
-    echo "FATAL ERROR: USAGE VARIABLE IS NON-NUMERIC: $swap_used, CANNOT CONTINUE!"
+    echo "FATAL ERROR: SWAP USED IS NON-NUMERIC: $swap_used, CANNOT CONTINUE!" 1>&2
     exit 1
 fi
 
 if [[ "$swap_used" -eq 0 ]]; then
-    echo "Current usage @ $swap_used MB, no need to flush, exiting early..."
+    echo "Current usage @ $swap_used MB, no need to flush, exiting early..." 1>&2
     exit 0
+fi
+
+memory_available="$(free -m | awk '/Mem:/{ print $NF }')"
+
+if [[ -z "$memory_available" ]]; then
+    echo "FATAL ERROR: MEMORY AVAILABLE IS EMPTY: $memory_available, CANNOT CONTINUE!" 1>&2
+    exit 1
+fi
+
+if ! [ "$memory_available" -eq "$memory_available" ] 2>/dev/null; then
+    echo "FATAL ERROR: MEMORY AVAILABLE IS NON-NUMERIC: $memory_available, CANNOT CONTINUE!" 1>&2
+    exit 1
+fi
+
+if [[ $swap_used -ge $memory_available ]]; then
+    echo "FATAL ERROR: NOT ENOUGH AVAILABLE MEMORY TO MOVE TO FROM SWAP; CURRENT SWAP USED IS $swap_used and $memory_available IS AVAILABLE." 1>&2
+    exit 1
 fi
 
 echo "Current usage @ $swap_used MB, turning swap off temporarily to flush contents..."
